@startuml

package backend{
    package Model{

        class Creature
        class Game
        class Player
        class Inventory
        class Item
        class Purse
        class Monster

        Game        -->     Creature 

        Creature    <|-    Player
        Creature    <|-    Monster

        Creature    -->     Item
        Creature    *--     Inventory
        Inventory   *-     Purse
        Inventory   -->     Item
    }
}

package client{

    package View{
        class Main
        class Business_scripts

        Main --> Game
        Main *- Business_scripts
    }
}

@enduml