@startuml
skinparam monochrome reverse
class "GameEntity"{
    + state
}
note left: STATES\n - playable\n - npc\n - lifeless

class "Character"
class "Item"
class "User"
class "Game"

User --* GameEntity : plays
GameEntity -* Game : Participates

GameEntity <|-- Character
GameEntity <|-- Item

@enduml