@startuml

class "GameEntity"
class "Character"
class "Item"
class "User"
class "Game"


User --* GameEntity : plays
GameEntity -* Game : Participates

GameEntity <|-- Character
GameEntity <|-- Item

@enduml